-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    uid INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    address VARCHAR NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    balance DECIMAL(10, 2) NOT NULL DEFAULT 0.00 CHECK (balance >= 0.00), --constraint balance > 0
    isSeller BOOLEAN DEFAULT FALSE,
    cartid INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (uid, email)
);

--withdraw needs to be a function to add or remove balance
--pubProfile should be a view from User (name, accountID, PubProfileID)

CREATE TABLE Seller (
    address VARCHAR NOT NULL REFERENCES Users(address),
    email VARCHAR REFERENCES Users(email),
    uid INT NOT NULL REFERENCES Users(uid),
    PRIMARY KEY (uid)
);

CREATE TABLE Products (
    productid INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    description VARCHAR(255),
    category VARCHAR(255) UNIQUE NOT NULL
    available BOOLEAN DEFAULT TRUE,
    img_path  VARCHAR(255) DEFAULT NULL,
    avg_rating DECIMAL DEFAULT 0,
    seller_id INT REFERENCES Users (id) DEFAULT NULL,
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(uid),
    pid INT NOT NULL REFERENCES Products(productid),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE ProductsForSale ( -- do we need price here
    productid INT NOT NULL REFERENCES Products(productid),
    uid INT NOT NULL REFERENCES Seller(uid),
    quantity INT NOT NULL,
    PRIMARY KEY (productid, uid)
);

CREATE TABLE OrdersInProgress (
    address VARCHAR NOT NULL REFERENCES Users(address),
    date timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    quantities INT NOT NULL REFERENCES LineItem(quantities),
    orderid INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT,
    status BOOLEAN DEFAULT FALSE,
    productid INT NOT NULL REFERENCES Products(productid)
);

CREATE TABLE Cart (
    cartid INT NOT NULL PRIMARY KEY REFERENCES Users(cartid),
    uniqueItemCount INT NOT NULL 
); 

CREATE TABLE LineItem (
    cartid INT NOT NULL REFERENCES Cart(cartid),
    productid INT NOT NULL REFERENCES Products(productid),
    quantities INT NOT NULL,
    totalPrice DECIMAL(65,2) NOT NULL,
    status BOOLEAN REFERENCES OrdersInProgress(status),
    date timestamp REFERENCES OrdersInProgress(date),
    PRIMARY KEY (cardid, productid)
);

CREATE TABLE ProductReviews (
    productid INT NOT NULL REFERENCES Products(productid),
    uid INT NOT NULL REFERENCES Users(uid),
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comments VARCHAR(255),
    date timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    PRIMARY KEY (productid, uid)
);

CREATE TABLE SellerReviews (
    sellerid INT NOT NULL REFERENCES Seller(uid),
    uid INT NOT NULL REFERENCES Users(uid),
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comments VARCHAR(255),
    date timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    PRIMARY KEY (sellerid, uid)
);
